### ISSUE TITLE
I'm trying to authenticate with GitHub

### ISSUE THREAD

**Issue by JZ-at-TP** [nxtbgthng/OAuth2Client#104]
I've got it setup as:

<code>[[NXOAuth2AccountStore sharedStore] setClientID:@"CLIENT"
                                             secret:@"SECRET"
                                              scope:[NSSet setWithObjects:nil]
                                   authorizationURL:[NSURL URLWithString:@"https://github.com/login/oauth/authorize"]
                                           tokenURL:[NSURL URLWithString:@"https://github.com/login/oauth/access_token"]
                                        redirectURL:[NSURL URLWithString:@"http://dashboard.goonies3.com/auth/github/callback"]
                                     forAccountType:@"GitHub"];
</code>

but when I try to auth with:

<code>[[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:@"GitHub"
                                                              username: self.username.text
                                                              password: self.password.text];
</code>

I keep getting:

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'No token from token response: {"error":"bad_verification_code"}'

What am I doing wrong?

**Comment by toto** [comment]
You are hitting an assertion (try adding a symbolic breakpoint on `-[NSException raise]` to see where exactly - `NXOAuth2AccessToken.m` in this case). 

It seems Github does not support the OAuth2 username/password flow. Try the external browser method.

**Comment by JZ-at-TP** [comment]
Hmm. When I try auth external browser method with <code>[[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:@"GitHub"];</code> I get:

<code>2014-01-28 13:30:26.686 Dashboard[72249:70b] -[NSURL nxoauth2_URLByAddingParameters:]: unrecognized selector sent to instance 0x8aa6e50
2014-01-28 13:30:26.690 Dashboard[72249:70b] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURL nxoauth2_URLByAddingParameters:]: unrecognized selector sent to instance 0x8aa6e50'</code>

So I'm not sure what's going on.
