### ISSUE TITLE
Manually refreshing AccessToken causes an Exception

### ISSUE THREAD

**Issue by zvaehn** [nxtbgthng/OAuth2Client#114]
First of all: Thanks for the Code!

I am able to use the OAuth flow in my Application, but when the accessToken expires, i am manually calling `[[NXOAuth2AccountStore sharedStore] refreshAccessToken];` to get a new accessToken.

It throws an Exception shown below:
`-[NXOAuth2AccountStore refreshAccessToken]: unrecognized selector sent to instance`

Is it a bug or am i just unable to solve this in, for now, at least 3 days?

**Comment by toto** [comment]
that is because `refreshAccessToken` is specified on `NXOAuth2Client` not on the account store. Manual refresh needs to be done using `NXOAuth2Client`.

**Comment by zvaehn** [comment]
Just for my understandings:
The `performRequest` method on NXOAuth2Request refreshes the AccessToken automatically, but the "the good old way" (how you call it), don't do it. So i have to refresh my token automatically after checking if it has been expired?
