### ISSUE TITLE
LinkedIn Authentication not working anymore in 1.2.6

### ISSUE THREAD

**Issue by Rayito-M** [nxtbgthng/OAuth2Client#118]
Hi,

following this given example : http://www.idmworks.com/blog/entry/getting-started-with-oauth2client-on-ios

I was able to make work the OAuth2 with Linkedin. Since I'm using the new 1.2.6 version I get this error:

oauthConnection Error: {"error":"invalid_request","error_description":"missing required parameters, includes an invalid parameter value, parameter more than once. : client_id"}
2014-06-23 17:31:42.456 Smoobility[41908:3399762] Error on NOT DEFINED OAuth with decription HTTP Error: 400

(going back to old version by just changing the subproject is back to work)

Best,

Christophe

**Comment by konkontos** [comment]
I was facing the same problem. Finally had success by altering the following code in NXOAuth2Connection.m

`- (void)applyParameters:(NSDictionary *)parameters onRequest:(NSMutableURLRequest *)aRequest;`

to force sending POST/PUT requests as application/x-www-form-urlencoded.

**Comment by toto** [comment]
Version1.2.8 is available and fixes this issue

**Comment by konkontos** [comment]
I'm sorry but I initially downloaded and used 1.2.8.
I was not able to retrieve an authentication token from LinkedIn using the library code as is.
