### ISSUE TITLE
Incompatible pointer types

### ISSUE THREAD

**Issue by doc-iwatersports** [nxtbgthng/OAuth2Client#120]
I recieved the following on a new install of the development branch.

ProjectDir/Pods/NXOAuth2Client/Sources/OAuth2Client/NXOAuth2PostBodyPart.m:42:52:
Incompatible pointer types sending 'CGPathRef' (aka 'const struct CGPath *') to parameter of type 'NSString *'
Here is the code.

```
return [self initWithName:name fileContent:[content path]];
```

This:

```
return [self initWithName:name fileContent:[NSString stringWithFormat:@"%@",[content path]]];
```

will fix it, however, it may not be a problem as it shows up in a future version of XCode.

**Comment by stigi** [comment]
Seems Xcode is having a problem resolving `content` to the proper type. Might think it's of type `id` and therefore think that `-path` is a method from `UIBezierPath`...

A simple cast might help: `return [self initWithName:name fileContent:[(NSURL *)content path]];` and also be the cleanest solution considering the class check 1 line above.

**Comment by doc-iwatersports** [comment]
That works, thanks.
