### ISSUE TITLE
Support RESTful PATCH

### ISSUE THREAD

**Issue by doc-iwatersports** [nxtbgthng/OAuth2Client#131]
Is there a reason that the library doesn't support the Http method=PATCH in [NXOAuth2Request performMethod:@"PATCH"

```
 if ([httpMethod caseInsensitiveCompare:@"POST"] != NSOrderedSame
&& [httpMethod caseInsensitiveCompare:@"PUT"] != NSOrderedSame) {
       aRequest.URL = [aRequest.URL nxoauth2_URLByAddingParameters:someParameters];
} else {
```

is the solution to overload NXOAuth2Request class or is this an umimplemented feature that I should fix and submit a pull request for?

Suggested Solution

```
if ([@[@"POST",@"PUT",@"PATCH"] containsObject: [httpMethod uppercaseString]]) {
        aRequest.URL = [aRequest.URL nxoauth2_URLByAddingParameters:someParameters];
} else {
```

**Comment by toto** [comment]
Indeed we just overlooked the `PATCH` verb as it was mostly used for WebDAV at the time the library was first created. Times change it seems. `PATCH` should be supported

Feel free to create a pull request against the `develop` branch. I will merge it asap.
