### ISSUE TITLE
refreshAccessToken doesn't use customHeaderFields

### ISSUE THREAD

**Issue by Out1and3r** [nxtbgthng/OAuth2Client#138]
Hi.

I found that "refreshAccessTokenAndRetryConnection" method doesn't set the "customHeaderFields" data into the call. Could you please modify <code>-(void)refreshAccessTokenAndRetryConnection:(NXOAuth2Connection *)retryConnection </code> method. The following code should be added:

```
if (self.customHeaderFields) {
    [self.customHeaderFields enumerateKeysAndObjectsUsingBlock:
    ^(NSString *key, NSString *obj, BOOL *stop) {
            [tokenRequest addValue:obj forHTTPHeaderField:key];
    }];
}
```

Thanks.

**Comment by toto** [comment]
Can you prepare a pull request with this?

**Comment by miktav** [comment]
Agreed, this is a necessary change. Thanks for an excellent library, it is tremendously helpful.

**Comment by SeverinWeber** [comment]
had the same problem, still not fixed in the actual version.

**Comment by trentmilton** [comment]
Is there any plans to fix this soon?

**Comment by trentmilton** [comment]
Actually it seems to be fixed in this pull request https://github.com/nxtbgthng/OAuth2Client/pull/181

**Comment by va7map** [comment]
@toto would you consider pulling this in? We ran into the same problem and this will definitely fix it.

**Comment by toto** [comment]
@va7map Done. Should have been done weeks ago. Sorry

**Comment by va7map** [comment]
@toto not a problem! Thanks for the quick reply.
