### ISSUE TITLE
NXOAuth2Request not using signed requests

### ISSUE THREAD

**Issue by hiDominik** [nxtbgthng/OAuth2Client#141]
Hi!

in the NXOAuth2Request class, the method `signedURLRequest` is never used, but on sending these requests, you actually want to have an authenticated request.

Is there a reason that just a normal request is used in the `performRequestWithSendinProgressHandler:responseHandler:` that I'm not seeing right now, or is there a way to set a fully prepared NSURLRequest from outside this pod/library?

My suggestion would be to use `[self signedURLRequest]` to include all necessary Header fields and parameters in the 'perform' method instead of creating an NSMutableURLRequest including only the URL and the HTTP method.

Cheers,
Dom

**Comment by olegueret** [comment]
Yes, there is a way (and a reason) to use a fully prepared NSURLRequest outside this library (in fact is documented in the README, look at the paragraph [Getting a signed NSURLRequest](https://github.com/nxtbgthng/OAuth2Client#getting-a-signed-nsurlrequest)). 

This can be used to authenticate requests done with 3rd party networking libraries like [AFNetworking](https://github.com/AFNetworking/AFNetworking).

**Comment by toto** [comment]
Note that this is a three step process:
1. Initialize a `NXOAuth2Request` object
2. Set it's `account` property to your `NXOAuth2Account`
3. Use `-signedURLRequest`

If you forget step 2 it will work as a URL request, but will be missing the authentication header - which defeats it's purpose.

**Comment by hiDominik** [comment]
But my problem is, when I call `[NXOAuth2Request performMethod...]` the sent request is not signed.

using the request outside of the library does make sense, but there is currently no way to have this library use the signed request, right?

**Comment by hiDominik** [comment]
I just checked it again (with the version you just released), and now it works just as expected. Could also have been just a glitch on the server I'm trying to connect to.

I'll close this issue, thanks a lot for your help!
