### ISSUE TITLE
NXOAuth2Request signedURLRequest not working since "Add support for http method PATCH" commit

### ISSUE THREAD

**Issue by olegueret** [nxtbgthng/OAuth2Client#142]
When performing signed requests with NXOAuth2Request's method `signedURLRequest`, the GET requests are configured with multipart/form-data, while POST, PUT and PATCH don't, which obviously should be the opposite way.

The problem seems to have been introduced by this commit: 4974dafa77ecaba9fe586c383072edf975b3202e

Shouldn't the IF in the applyParameters:onRequest: method be negated in order to work as intended?

```
if (![@[@"POST",@"PUT",@"PATCH"] containsObject: [httpMethod uppercaseString]]) {
```

**Comment by toto** [comment]
That is indeed true, of course the if needs to be negated.

**Comment by toto** [comment]
Fixed in cf36ae1e1b134be4b0f75aa3d4e5c1602e5917fc on develop

**Comment by olegueret** [comment]
Thank's @toto, that was super-fast!

**Comment by toto** [comment]
It was a super serious problem and I was a bit ashamed I overlooked this when looking at the PR that introduces the problem.
