### ISSUE TITLE
Can never find NXOAuth2.h

### ISSUE THREAD

**Issue by KieranLafferty** [nxtbgthng/OAuth2Client#15]
Hello, I followed all the steps

1) Had to track down my libOAuth2Client.a manually via the debug simulator build folder and drag it to the Debug folder where the OAuth2Client.framework was successfully placed

2) Adding the "/tmp/OAuth2Client.dst/usr/local/include" to user header paths for both Target and Project, and both individually still nothing.

3) Using Xcode 4.1, building to iOS 4.3 simulator

Could you please post a sample project with it linked properly for reference. I feel as though I have tried every possible variation of the instructions to get it working please help!

Thanks,

Kieran

**Comment by kainosnoema** [comment]
@KieranLafferty I discovered you have to tweak the project a bit to get it to build in Xcode 4.x:
1. Assuming you've already added OAuth2Client.xcodeproj to your project, click on it, select the OAuth2Client target (not the .framework) under the Targets section, then click on the Build Phases tab on the right.
2. Under the Copy Headers section, move (select and drag) all the headers listed in Project list to the Public list.

As long as you've followed the other instructions in the Readme, it now it should build properly.

@nxtbgthng in Xcode 4, only headers in the Public section will be copied to the build directory. You should probably update the project to handle this a bit better.

**Comment by ionutale** [comment]
hi everyone,

I still have the same issue!
I did everything as told here https://github.com/nxtbgthng/OAuth2Client#ios-projects
Then i moved all the OAuth headers from the project into the public.

But i still get the same error.

I just downloaded the framework, so is the latest version ( downloaded from here https://github.com/nxtbgthng/OAuth2Client#ios-projects )

please help me up 
I really need this library and for the first time i am under pressure of time. i have only 2 days to finish this project.
I really appreciate the help.
Thanks

kind regards
AiU

**Comment by stigi** [comment]
@jhonyourangel:

did you consider using cocoapods?

If not can you please post your `Header Search Path` build setting?

**Comment by ionutale** [comment]
here it is
This is from my project target ( and not from the framework target )
$(inherited) /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include $(SRCROOT)/path/to/OAuth2Client

**Comment by stigi** [comment]
did you check the `recursive` checkmark for the OAuth2Client path?

**Comment by ionutale** [comment]
no i didn't.

But i can't find where is it ?!

where can i find it ?

( thanks allot )

**Comment by stigi** [comment]
That would be (in Xcode 5) right of the path. There you can select recursive/non-recursive. Non-recursive is the default.
![screen shot 2013-12-02 at 11 52 19](https://f.cloud.github.com/assets/13815/1653941/ddc35494-5b3f-11e3-8862-d173e551676b.png)

**Comment by ionutale** [comment]
ok, something is different on my project 
i don't have the table rows like you, ia have an unique string row :
![my app screenshoot](https://f.cloud.github.com/assets/2562455/1653965/a9ab9c56-5b40-11e3-9800-4f7830ca5839.png)

i have xCode 5.0

**Comment by ionutale** [comment]
:))))))

double click on the row did the trick 

testing now if the error is still there

**Comment by stigi** [comment]
Xcode does only seem to open the popup by quickly double clicking on the setting.

**Comment by ionutale** [comment]
![my app ss2](https://f.cloud.github.com/assets/2562455/1653990/427aed92-5b41-11e3-84ba-e4d48402d34e.png)
stil have the error

( haven't use this side of the xcode, 'cause is easy to broke everything. that's why i so herd to comprehend ... )

**Comment by stigi** [comment]
did you try to change `path/to/OAuth2Client` for the correct path??

**Comment by ionutale** [comment]
no!

so, i go to the OAuth2Client.xcodeproj get info, and link it ?

**Comment by stigi** [comment]
you need to change the value you added to your `Header Search Path` to the directory where you put the OAuth2Client...

**Comment by ionutale** [comment]
i'm having problems with the path
the name of the app contains " " (white space ) and is gen me more than one row in the "search path..."

i'l make a new project, in a directory without " " just to check if is working.
I'l let you know in 5 min

**Comment by ionutale** [comment]
ok, so i have the same error

dum question: the #import "NXOAuth2.h", where should i put it ?
i put it in the Application delegate .m file, because more likely first things will happen there ( in my app )

the path for the OAuthClient that i added is:
$/Users/ionutale/Desktop/client/OAuth2Client-master/path/to/OAuth2Client

( hope is not a risk to post the path ?! )

**Comment by stigi** [comment]
If the name contains whitespace just wrap the entire parameter in quotes.

**Comment by ionutale** [comment]
interesting ( is the basic string way "" )
i have created a new project, in a path that doesn't contain white spaces.
i made a video, creating a project and adding the framework, is uploading to youtube right now.

The only thing is that i haven't added the actual path but the "$(SRCROOT)/path/to/OAuth2Client". 
hope is not a problem...

**Comment by ionutale** [comment]
here is the video, hope it helps 
http://www.youtube.com/watch?v=3vui3DDPF6k&feature=youtu.be

i was low on ram memory, so the quality is not optimal ( sorry about that )

*******_edit ***_*******
probably i did it:
added this path: $(SRCROOT)/OAuth2Client-master/Sources
i get an "ignoring framework warning":
ld: warning: ignoring file /Users/ionutale/Library/Developer/Xcode/DerivedData/client-csrxnfptxgncaefrvhklvcxotkqz/Build/Products/Debug-iphonesimulator/libOAuth2Client.a, file was built for archive which is not the architecture being linked (x86_64): /Users/ionutale/Library/Developer/Xcode/DerivedData/client-csrxnfptxgncaefrvhklvcxotkqz/Build/Products/Debug-iphonesimulator/libOAuth2Client.a

i will make a few test to see if the framework "is NOT ignored, and actually works".
i'll keep you posted.

**Comment by manjulayel** [comment]
hello,
 i am also facing same problem header not found could you help me on this , i done everyhting what you said but still i am facing same problem

**Comment by manjulayel** [comment]
I really need help, i am struggling near 2 days onwards ,but nothing improvement.advancely thanks for help

**Comment by anagromataf** [comment]
@manjulayel Can you explain you problem a bit?

**Comment by stigi** [comment]
@manjulayel I can only emphasize on my recommendation to use CocoaPods. The problem you're describing could be caused by a million things, tiny or small. Using CocoaPods will eliminate most of them and also help you with integrating other open source libraries. It's just the right thing to do.

**Comment by manjulayel** [comment]
Hello,
           Thank you for reply,

While compiling  OAuth2Client.xcodeproject its giving this error,

_target specifies product type 'com.apple.product-type.framework', but
there's no such product type for the 'iphonesimulator' platform "._
-     I Changed Build SDK to *_iOS and i selected device its showing that
  error,what i have to do for that ,i searched in google ,I tried so many
  ways but still same problem._

**Comment by manjulayel** [comment]
Hello,

```
      Thanks for reply one more doubt will we implement without webview
```

by using oauth2client framework ,is it possible.
I f possible can you give some sample code.

```
  thanks advancely.
```

**Comment by chrbongardt** [comment]
It is already documented. See the section `Requesting Access to a Service` : Username and Password of the README.md

**Comment by manjulayel** [comment]
I tried to pass my credentials by this method ,but its not store because of this reason ,i requesting for any url its crashing ,
i tried like this
 [[NXOAuth2Client alloc] initWithClientID:kIDMOAuth2ClientId
clientSecret:kIDMOAuth2ClientSecret
authorizeURL:[NSURL URLWithString:kIDMOAuth2AuthorizationURL]
tokenURL:[NSURL URLWithString:kIDMOAuth2TokenURL]
delegate:self];

 this is way also tried still not getting,
  [[NXOAuth2AccountStore sharedStore] setClientID:kIDMOAuth2ClientId
                                             secret:kIDMOAuth2ClientSecret
                                              scope:[NSSet setWithObject:kIDMOAuth2Scope]
                                   authorizationURL:[NSURL URLWithString:kIDMOAuth2AuthorizationURL]
                                           tokenURL:[NSURL URLWithString:kIDMOAuth2TokenURL]
                                        redirectURL:[NSURL URLWithString:kIDMOAuth2RedirectURL]
                                     forAccountType:kIDMOAuth2AccountType]; 

if i requested for this url 
 [[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:@"https://www.google.com/accounts/ClientLogin"
                                                              username:@"manjula@gmail.com"
                                                              password:@"xxxxx"];
app is crashing

could you give response for this,i a m really awaiting for your response.

**Comment by stigi** [comment]
@manjulayel we're moving quite off topic here.

You solved the issues that the headers could not be found?

Could you then please create a new issue for the other problems you're having?  
And could you also please take some time to read through the markdown specs [here](https://help.github.com/articles/github-flavored-markdown) and [here](https://help.github.com/articles/markdown-basics). This will make your posts more readable and will highly increase the probability of people helping you.

Thanks

**Comment by manjulayel** [comment]
Hello Ullrich,

```
          Thanks for reply ,i started this application almost 3 days
```

onwards, for header could not find is solved just one day back.After
solving that problem i am getting this crash issue,so i raised this problem
to you people.For each and every problem if i spend more than 2 days then
when my app will be closed.Anyway thanks again i won't mail you people next
time.Myself i tried,if not happening i will leave this library and i will
start other approach.

Thanks
manjulayel

**Comment by chrbongardt** [comment]
Manjulayel, you do know that this library is free, right ? Sounds like you're complaining about something you payed for, instead of thanking for it ;)

**Comment by manjulayel** [comment]
Hello,

```
  I really  appreciating you people for helping to other people,i am
```

not sounding sir,i am just explaining my problem.I am really struggling by
implementing oauth2.Thats why i approached you people.Anyway thanks sir.

Thanks
manjula

**Comment by chrbongardt** [comment]
They are doing a great job, I agree on that.
