### ISSUE TITLE
[NXOAuth2PostBodyStream open] Stream has been reopened after close

### ISSUE THREAD

**Issue by ger86** [nxtbgthng/OAuth2Client#17]
I'm developing an ios application.

In my appdelegate i have:
- (void)initialize;
  {
  [[NXOAuth2AccountStore sharedStore] setClientID:@".....t"
                                           secret:@"...."
                                 authorizationURL:[NSURL URLWithString:@"http://XXX/oauth/authorize"]
                                         tokenURL:[NSURL URLWithString:@"http://XXX/oauth/token"]
                                      redirectURL:[NSURL URLWithString:@"http://XXX"]
                                   forAccountType:@"myFancyService"];
  }

and in a view controller i have a button that calls:
- (IBAction)buttonPressed:(id)sender {
  
  [[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:@"myFancyService"
                                                            username:@"XXX"
                                                            password:@"XX"];
  }

But i get in the log the following message:

[NXOAuth2PostBodyStream open] Stream has been reopened after close

any idea?

**Comment by anagromataf** [comment]
This looks like the problem we fixed in version 1.0.1.
Please try this version and look if your problem is still there.

**Comment by ger86** [comment]
I'm using 1.0.1 (the code changed from 1.0 is shown here : https://github.com/nxtbgthng/OAuth2Client/commit/35865c6d586d1b97621631c1bd29382fc61b1866) but i still have my problem. 

Any idea? It works when i use  

[[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:@"myFancyService"]

without more arguments.

Thanks!

**Comment by anagromataf** [comment]
I just tired it with an OAuth2 service, that supports the username/password authorization low and it worked. Maybe the service you are using does not provide this flow?

Have you looked into the network traffic. For instance with http://www.charlesproxy.com/?

Cheers,
Tobias.

**Comment by ger86** [comment]
Sorry my web service was wrong. But i have another question.

When i call:

[[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:
@"myFancyService"];

the application opens the safari mobile app. Is it normal? is possible to
embed that call in a UiWebView?

Thanks!

Gerardo Fernndez Moreno

Clases de Apoyo - www.clasesdeapoyo.com
tw: @ger86 http://www.twitter.com/ger86

2012/1/10 Tobias Krntzer <
reply@reply.github.com

**Comment by anagromataf** [comment]
You can use this method and provide a block which opens the web view `- [NXOAuth2AccountStore  requestAccessToAccountWithType: withPreparedAuthorizationURLHandler:]`. In the delegate of the web view you have to call `- [NXOAuth2AccountStore handleRedirectURL:]`. This method will return `YES` if the URL has been handled by the OAth2 framework.

Have a look at https://github.com/soundcloud/CocoaSoundCloudUI/blob/master/Sources/SoundCloudUI/SCLoginView.m#L118 which uses the OAuth2 Framework.

**Comment by ger86** [comment]
Hi, thanks. It works excellent. But i have another question.

The token request uses a POST request. Is it possible to modify it in order
to use a GET request?

Thanks!

Gerardo Fernndez Moreno

Clases de Apoyo - www.clasesdeapoyo.com
tw: @ger86 http://www.twitter.com/ger86

2012/1/11 Tobias Krntzer <
reply@reply.github.com

**Comment by ger86** [comment]
And i have another dubt.

Do you know if your library works with Twitter OAuth2 ? I'm trying to make
it work but i can't. Have you proved it?

I want to thank you your replies. They are very useful for me.

Gerardo Fernndez Moreno

Clases de Apoyo - www.clasesdeapoyo.com
tw: @ger86 http://www.twitter.com/ger86

2012/1/14 Gerardo Fernndez gefe.86@gmail.com

**Comment by anagromataf** [comment]
Regarding the POST request:

I'm not so deep into this part of the framework and the OAuth2 specs. But I guess you just need to change these requests to GET.

https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2Client.m#L243

We are using this framework in the first place for the SoundCloud API, but it should work with other OAuth2 servers. Keep in mind that this framework implements draft 10 of the OAuth2 spec.

**Comment by joshholat** [comment]
I'm getting the `-[NXOAuth2PostBodyStream open] Stream has been reopened after close` error as well. Specifically, it appears to be happening here in `NXOAuth2Client.m`:

```
// Web Server Flow only
- (void)requestTokenWithAuthGrant:(NSString *)authGrant redirectURL:(NSURL *)redirectURL;
{
    ...
    authConnection = [[NXOAuth2Connection alloc] initWithRequest:tokenRequest
                                               requestParameters:parameters
                                                     oauthClient:self
                                                        delegate:self];
    authConnection.context = NXOAuth2ClientConnectionContextTokenRequest;
}
```

I get can past the initial request to get the request token, but this second request to get the access token appears to be failing. Could you perhaps explain what might cause this to occur inside of the framework so that I can have a better shot at debugging it?

**Comment by RobertAudi** [comment]
I get the same error message, even though everything seems to work properly... Details in [this SO question](http://stackoverflow.com/questions/15874093/ios-oauth2client-custom-url-schemes-and-nsnotificationcenter)
