### ISSUE TITLE
Authorization: OAuth

### ISSUE THREAD

**Issue by halkeye** [nxtbgthng/OAuth2Client#18]
Which draft supports "Authorization: OAuth ..."?

The provider I'm connecting to is expecting "Authorization: Bearer ..."

(see http://tools.ietf.org/html/draft-ietf-oauth-v2-22 7.1)

Should the code be fixed? or make this customizable?

**Comment by anagromataf** [comment]
This library is based on draft 10 of the OAuth2 spec. There are no plans to update it to a new draft at the moment.
