### ISSUE TITLE
broken encoding with python 3.4 (fix inside)

### ISSUE THREAD

**Issue by richiverse** [nxtbgthng/OAuth2Client#187]
context:

``` bash
.../site-packages/oauth2client/client.py", line 1515, in __init__
self.private_key = base64.b64encode(private_key) 
File ".../venv/lib/python3.4/base64.py", line 62, in b64encode
encoded = binascii.b2a_base64(s)[:-1]
TypeError: 'str' does not support the buffer interface
```

Changing line 1515 in oauth2client/client.py from this:

``` python
self.private_key = base64.b64encode(private_key)
```

to this:

``` python
self.private_key = base64.b64encode(private_key.encode('ascii'))
```

fixed my issue.

reference:
http://stackoverflow.com/questions/27160352/when-convert-to-base-64-typeerror-str-does-not-support-the-buffer-interface

**Comment by toto** [comment]
I think you have the wrong OAuth2Client. This is an iOS/OS X library for OAuth 2, not python.
