### ISSUE TITLE
OAuth with UiWebView And SSL

### ISSUE THREAD

**Issue by Sravanik84** [nxtbgthng/OAuth2Client#198]
Hi team, I am trying to get access token (get authenticated) using a UIWebView. I am receiving the SSL certificate error immediately after hitting the url.

Code: 
 [[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:kIDMOAuth2AccountType
                                   withPreparedAuthorizationURLHandler:^(NSURL *preparedURL){

```
                                   //navigate to the URL returned by NXOAuth2Client
                                   [self.loginWebView loadRequest:[NSURLRequest requestWithURL:preparedURL]];
                               }];
```

Error:
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)

I need to authenticate in webview because i need the auth server web session id, for further loading the other urls. I am able to get the access token with user name and password, however I am not able to load the other urls with access token as they need the web session id.
1. How do I get rid of the error posted above, if I want to be authenticated via UIWebvIew?
2. If authenticated with user & password, can I get auth server web session id?

Please provide some details in which direction I should move forward. This became a big blocker for my app now.

**Comment by toto** [comment]
I think you are running into App Transport Security. Take a look at the [iOS 9 release notes](https://developer.apple.com/library/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html)
