### ISSUE TITLE
Could anyone please provide a demo project?

### ISSUE THREAD

**Issue by flypigz** [nxtbgthng/OAuth2Client#22]
thanks...

**Comment by flypigz** [comment]
anyone can help? thanks

**Comment by anagromataf** [comment]
It is indeed a good idea to have a demo project only using the OAuthClient, But many you find your answers in the SoundCloud API wrapper, where we are using this project.

https://github.com/soundcloud/CocoaSoundCloudAPI
https://github.com/soundcloud/CocoaSoundCloudDemo

If not, don't hesitate to ask you questions.

**Comment by sleeke** [comment]
I can't seem to get the CocoaSoundCloudAPI project to build on XCode 4.2 - it keeps coming back with 'OAuth2Client/NXOAuth2.h' file not found. This is the same error I get when trying to build my own project using the OAuth2Client project using the instructions at 

https://github.com/nxtbgthng/OAuth2Client

I have followed the instructions to the letter, and also tried the suggestion posted here...

https://github.com/nxtbgthng/OAuth2Client/issues/15

...but have had no luck with that either. Can anyone suggest any solutions to this issue? It's driving me nuts!

Thanks

**Comment by anagromataf** [comment]
Did you had a look at the project layout of [CocoaSoundCloudDemo](https://github.com/soundcloud/CocoaSoundCloudDemo)? Have you checked out this project an got it running?

**Comment by sleeke** [comment]
I've checked out the project but can't seem to get it to build. When I load the workspace, there's only one Project (SoundShare) and the compiler complains about not being able to find "SCAPI.h"...

**Comment by anagromataf** [comment]
Have you updated the submodules?

```
git submodule update --init --recursive
```

**Comment by sleeke** [comment]
I'm not using GIT, I'm just downloading the source as a zip file. Will there be a difference?

**Comment by anagromataf** [comment]
Then you have to take care of the submodule stuff by hand. I would highly suggest you to use git. It makes it much more easy to keep the project (and its submodules) up to date.

**Comment by sleeke** [comment]
Thanks - I've done that and it builds now.

**Comment by stigi** [comment]
@sleeke: perfect. I'll close the issue

**Comment by RobertAudi** [comment]
Thanks for the demo app @anagromataf . But I did not manage to make the app run on the 5.0 and 6.1 SDKs; that are the only SDKs that I have installed. Also, I have a question about the code: When you configure NXOAuth2AccountStore, you provide an odd redirect URL: `soundshare://soundcloud`. I tried to provide a dummy URL for my app (`https://catapultcentral.com/iOSClientCallback`) but the app doesn't seem to catch it, so when I click on the authorize button on the OAuth server (which I opens in a webview) nothing happens. So how does the redirectURL work please?

**Comment by anagromataf** [comment]
Do you have some details, about the problem you ran into, while trying to build it for 5.0 or 6.1?

The Redirect URL must have a special protocol. E.g., "my-awesome-app://" and this has to be handled of your app.

**Comment by RobertAudi** [comment]
I get two error boxes as shown in ![this screenshot](http://dl.dropbox.com/u/155823/Slingshot/Pictures/Screen%20Shot%202013-03-26%20at%204.41.00%20PM.png). If I click on switch SDK I have the choice between the 5.0 SDK and 6.1 SDK. No matter what SDK I choose, when I click on Relaunch I get the same error messages.

About the redirect URL, how can I handle the special protocol?

**Comment by anagromataf** [comment]
This looks like you are having trouble with you Xcode. I just checked out the demo app and it compiles and runs.

The URL type can be set in the Info.plist of you app. 
![Bildschirmfoto 2013-03-26 um 17 53 51](https://f.cloud.github.com/assets/72718/304132/d36efd88-9635-11e2-8b9a-88f6abdcde7d.png)

Have a look at the [demo project](https://github.com/soundcloud/CocoaSoundCloudDemo/blob/master/SoundShare/SoundShare/SoundShare-Info.plist).
