### ISSUE TITLE
Possible addition to instructions

### ISSUE THREAD

**Issue by sleeke** [nxtbgthng/OAuth2Client#28]
@nxtbgthng Just a quick suggestion:

I had some issues building my project after adding the OAuth2Client project using your instructions and eventually traced the issue to the fat I hadn't included "Security.framework" - it might be worth adding this to your instructions in case others have the same issue...

Thanks! 

(Feel free to close this issue once you've read it)

**Comment by anagromataf** [comment]
We have scheduled some work on the documentation for this framework, but couldn't find the time to do this until now.
