### ISSUE TITLE
Problem using [NSString nxoauth2_stringWithUUID]

### ISSUE THREAD

**Issue by alexleigh** [nxtbgthng/OAuth2Client#34]
I'm using the latest version of OAuth2Client on the master branch with a project and I'm running into a strange issue that I can't figure out.  When I call `[[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:username:password:]` and the request succeeds, the app crashes with error `+[NSString nxoauth2_stringWithUUID]: unrecognized selector sent to class 0xc63fd8`.

I figured out this is from line 52 of NXOAuth2Account.m, `identifier = [NSString nxoauth2_stringWithUUID];` It seems the runtime can't find the NXOAuth2 category added to NSString, even though I followed the instructions in the README and added the OAuth2Client project to the build dependencies list, the linker list, and added OAuth2Client/*\* to the header search path. In fact, Xcode seems to be able to find that category. If I right click on the method call and choose "Jump to definition", Xcode shows me exactly where it is in NSString+NXOAuth2.m. Yet somehow when I run the program, that selector can't be found. Any idea what could be causing this?

**Comment by robb** [comment]
This is a known issue with the Linker. Please set the `Other Linker Flags` to `-ObjC load_all`.
See https://developer.apple.com/library/mac/#qa/qa2006/qa1490.html

**Comment by alexleigh** [comment]
Thanks! That worked perfectly.
