### ISSUE TITLE
Bug in NXOAuth2Client.m

### ISSUE THREAD

**Issue by ghost** [nxtbgthng/OAuth2Client#4]
NXOAuth2Client.m:133-136

Line 133: if there is no parameter key "error" in URL, then errorString is nil. In this case, the statement on line 136 will always return true because NSOrderedSame is enumerated to 0. An error object will be created and passed up to the app even though there is no error.

**Comment by stigi** [comment]
Client handling redirect URL without access grant and without error code did signal an invalid error to the delegate

Closed by de9f48de6d7ca667fa01d1ebb492ba12b7de76f8

**Comment by stigi** [comment]
Thanks for making me aware of this!
Comparing nil to NSOrderedSame is a real problem. Will step away from using caseInsensitiveCompare.
