### ISSUE TITLE
Using OAuth2Client with Flickr - Extra step in Authentication Flow?

### ISSUE THREAD

**Issue by ElmerCat** [nxtbgthng/OAuth2Client#43]
The framework is working beautifully for me with SoundCloud and WordPress. Thank you!

Now, I'm trying to add Flickr to my application's supported services, but they do things slightly differently and require getting an initial token before having the user authenticate as described here:

   http://www.flickr.com/services/api/auth.oauth.html

I don't see a straightforward way of getting the OAuth2Client framework to do this extra step in the authentication flow. Am I missing something obvious?

**Comment by ElmerCat** [comment]
Update - Well, I think the obvious thing I missed is that Flickr is using OAuth1 instead of OAuth2.

So, my question really is: does OAuth2Client provide compatibility with OAuth1 if I configure or use it in a different way?

If the short answer is "No", then could you suggest a Cocoa framework for OAuth1 that would play nicely in an app for which OAuth2Client is already working nicely?

**Comment by stigi** [comment]
No, OAuth1 & OAuth2 are not compatible in neither direction :)
I remember using [OAuthConsumer](http://code.google.com/p/oauthconsumer/) back in the days. Good luck with whatever you end up doing.

I'll close the issue. If you feel it should be reopened, fell free to do so.

**Comment by ElmerCat** [comment]
Thank you for that reference, I will check it out.

My application needs to read and write from multiple service providers, some of which are apparently still back in the olden days with OAuth1, so I'll have to come up with a way to handle both.

BTW - A usage note: I didn't realize the framework requires the redirectURL to be unique for each different accountType. My debugging eventually showed me how NXOAuth2AccountStore uses the redirectURL to determine the associated account (in handleRedirectURL). Perhaps a note about this in the ReadMe page will save new users the same trouble.

Thank you again for creating OAuth2Client; as of right now, it's working great in my OS X (10.8.2) Desktop app for reading and writing to SoundCloud and WordPress!
