### ISSUE TITLE
Cannot send anything other than strings in Params

### ISSUE THREAD

**Issue by squarefrog** [nxtbgthng/OAuth2Client#46]
If you pass in a dictionary containing anything other than NSStrings to +[NXOAuth2Request performMethod: onResource: usingParameters: withAccount:theAccount sendProgressHandler:] then NXOAuth2PostBodyPart triggers illegal type assertion.

**Comment by stigi** [comment]
"anything other than NSString" is not particularly true. Only for `GET` requests. For `PUT` and `POST` requests you can also pass in `NSData`, `NSURL` (as a file URL) and `NSStream` (see [NXOAuth2PostBodyPart.m#L35](https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2PostBodyPart.m#L35)).

What exactly are you trying to do? Using `NSValue`?

**Comment by squarefrog** [comment]
I realise this - I was using this method to send a dictionary of values to our webservice, so strings, ints, bools.. Perhaps it's a misunderstanding of the framework on my part..

**Comment by stigi** [comment]
@squarefrog I'm closing this issue for now. Feel free to open it if you're still running into problems.
