### ISSUE TITLE
NXOAuth2AccountStore is undefined symbol

### ISSUE THREAD

**Issue by EdwardHinkle** [nxtbgthng/OAuth2Client#48]
I followed the instructions in readme, and the app built successfully. Then I added:

[[NXOAuth2AccountStore sharedStore] setClientID:@"IDSTRING"
                                             secret:@"SECRETSTRING"
                                   authorizationURL:[NSURL URLWithString:@"https://domain/online/?q=oauth2/authorize/"]
                                           tokenURL:[NSURL URLWithString:@"https://domain/online/?q=oauth2/authorize"]
                                        redirectURL:[NSURL URLWithString:@"wm2://redirect"]
                                     forAccountType:@"otiAnywhere"];

Now it provides the following error:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_NXOAuth2AccountStore", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have my app set for iOS 5 target .... is there a problem with iOS 5 in regards to this library?

**Comment by stigi** [comment]
This is a linker error. Does it also occur when building for the device?
Maybe a clean all helps?

**Comment by thepost** [comment]
Same here. Followed the instructions, cleaned, deleted the Derived Data, deleted the app off the simulator, tried everything!

This kind of thing really is bullshit. This timewasting kind of shit shouldn't happen in 2013, it's exactly the thing that puts me off from using unsupported libraries in the first place. 

------ UPDATE:

Ok this might help some people: http://stackoverflow.com/questions/6984368/undefined-symbols-for-architecture-i386-objc-class-skpsmtpmessage-refere

**Comment by EnguYoo** [comment]
Is there any update on this issue ? I'm not having the problem when I `git clone` and manually add this project as a dependency, but I get it when using CocoaPods. Any clue ?

**Comment by toto** [comment]
This clearly is an issue with the way you link the project.If you are using Framework support in cocoapods  then this might be a source of the problem since this library so far has not been provided with that in mind.  I would suggest you try cocoapods for help.

**Comment by EnguYoo** [comment]
Indeed, it works on a simple project with just the Pod and a view. My bad, it should work fine on the other project too ! Thanks :)
