### ISSUE TITLE
access_token problems

### ISSUE THREAD

**Issue by kristersj** [nxtbgthng/OAuth2Client#58]
I wrote all the code that is in the read me for logging in.

The successful login notification is called, so the login has worked. 

I need to get the access_token - it should have been returned in some of the classes because the login was successful. 

Question - how i can access that access_token from my class? 

I see that it is in NXOAuth2Client class, but how do i get it in my class? I need to get it after the successful login notification to use it locally. 

Thanks in advance. Looks like a great open source.

**Comment by kristersj** [comment]
Also, how can I request a POST method using this open source?

**Comment by stigi** [comment]
You can always access the token via the oauthClient in your account.  
`account.oauthClient.accessToken`

The readme shows how to do a `GET` request. Doing a `POST` is quite similar:

```
[NXOAuth2Request performMethod:@"POST"
                    onResource:[NSURL URLWithString:@"https://...your service URL..."]
               usingParameters:@{"post-key":"post-value"}
                   withAccount:anAccount
           sendProgressHandler:^(unsigned long long bytesSend, unsigned long long bytesTotal) { // e.g., update a progress indicator }
               responseHandler:^(NSURLResponse *response, NSData *responseData, NSError *error){
                   // Process the response
               }];
```

**Comment by kristersj** [comment]
I try to get the access_token after successful login like this: 

NXOAuth2Account *account = [[NXOAuth2AccountStore sharedStore] accountWithIdentifier:@"testLogin"];
NSLog(@"Access token: %@", account.oauthClient.accessToken);

And I print it in NSLog, it is NULL. Do I create the account wrong or else?

Thanks.

**Comment by kristersj** [comment]
Am I creating the account incorrectly?

**Comment by minusplusminus** [comment]
```
   for (NXOAuth2Account *account in [[NXOAuth2AccountStore sharedStore] accounts]) {

    NXOAuth2Client *client =     [account oauthClient];
    NXOAuth2AccessToken *tokenData = [client accessToken];

    NSString * clientAccessToken = [tokenData accessToken];
    NSString * clientRefreshToken = [tokenData refreshToken];
 }
```

**Comment by kristersj** [comment]
@ikillbombs thank you!!! that does the job. 1 more thing - is there a method that clears all the existing accounts? - on logout i would like to call that one. Or i have to clear them myself?

**Comment by minusplusminus** [comment]
[[NXOAuth2AccountStore sharedStore] removeAccount:account];

**Comment by kristersj** [comment]
thank you very much for your help!
