### ISSUE TITLE
HTTPS with signed SSL certificate

### ISSUE THREAD

**Issue by raphaelha** [nxtbgthng/OAuth2Client#61]
Hi!

I don't undestand something about HTTPS  with signed certificate:

I assume I have to do this :

[[NXOAuth2AccountStore sharedStore] setTrustModeHandlerForAccountType:@"myAccountType" block:^NXOAuth2TrustMode(NXOAuth2Connection _connection,NSString_ hostname)
{
return NXOAuth2TrustModeSpecificCertificate;
}];

and something with this :

[[NXOAuth2AccountStore sharedStore] setTrustedCertificatesHandlerForAccountType:@"myAccountType" block:^NSArray*(NSString *hostname){
//What do I have to return there???????
}];

But what should I return in the block in setTrustedCertificatesHandlerForAccountType

**Comment by toto** [comment]
Hi!

First of all, sorry for the bad docs in this area. The two methods are used to support [certificate pinning](https://viaforensics.com/resources/reports/best-practices-ios-android-secure-mobile-development/41-certificate-pinning/). The basics are explained in [NXOauth2Constants.h:81](https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2Constants.h).

If you just want to use the default system trust (no pinning) just return `NXOAuth2TrustModeSystem` to trust any certificate chain that iOS/OS X trusts (i.e. no security warning when opening the site in Safari). For debugging `NXOAuth2TrustModeAnyCertificate` can be used. It should not be used in production though, as it will make you connections untrustworthy and make using SSL quite pointless.

If you want to use pinning, you need to return an array `NSData` objects containing the bytes of the trusted certificates for the particular hostname like this (provided you have api-cert-in-der-format.pem in your app's main bundle):

```
[[NXOAuth2AccountStore sharedStore] setTrustedCertificatesHandlerForAccountType:@"myAccountType" block:^NSArray*(NSString *hostname){
    return @[ [NSData dataWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"api-cert-in-der-format" ofType:@"der"]] ];
}
```

To convert a certificate in PEM format to DER you can use this command line: `openssl x509 -in cert.pem -inform PEM -out cert.der -outform DER`

To get the PEM formatted certificate copy the `--- BEGIN … END CERTIFICATE ---` block out of the result of this call (replacing nxtbgthng.com with your SSL host of course): `echo "HEAD / HTTP/1.0\n Host: nxtbgthng.com:443\n\n EOT\n" | openssl s_client -prexit -connect nxtbgthng.com:443`

**Comment by toto** [comment]
I will add docs making clear what needs to be returned.

**Comment by raphaelha** [comment]
Thanks a lot for your great answer! I will do this as soon as possible and let you know!

**Comment by toto** [comment]
I also documented this in the Wiki now: https://github.com/nxtbgthng/OAuth2Client/wiki/SSL-TLS-Certificate-Pinning

**Comment by stigi** [comment]
I'm closing this issue for now. Feel free to continue the discussion and reopen the issue if necessary.
