### ISSUE TITLE
Ability to pass parameters as query string for POST/PUT requests? [linkedin, facebook]

### ISSUE THREAD

**Issue by airdrummingfool** [nxtbgthng/OAuth2Client#72]
Some OAuth2 APIs, such as LinkedIn and Facebook, expect the token request parameters to be part of the URL query string instead of the HTTP POST request body as specified in the spec. Is there a way to do that with this library?

Ref: http://developer.linkedin.com/comment/22973#comment-22973

**Comment by stigi** [comment]
Hi,

according the the oauth2 spec the token request parameters are sent in the POST body. I don't know why Facebook & Linkedin are doing it differently. But it might make sense to offer a flag for those kind of APIs. I'm opening another issue to collect those APIs and to evaluate the necessity of such a move.

Thanks
