### ISSUE TITLE
UserData not being set

### ISSUE THREAD

**Issue by RobertAudi** [nxtbgthng/OAuth2Client#74]
I am developing an app that uses the OAuth2Client library. At some point I add some user data to the keychain item, or so I believed. Here is the code:

```
NXOAuth2Account *account = [[NXOAuth2AccountStore sharedStore] accountWithIdentifier:accountID];

// ...

FMResultSet *savedAccount = [self.db executeQuery:@"select forename, surname, account_name, client_name, smallest_logo from accounts where account_name = ? limit 1", accountName];

if ([savedAccount next]) {
    createdAccount = [savedAccount resultDictionary];
    [account setUserData:createdAccount];
}
```

For some reason, when I retrieve the account, the user data is not set/available...

```
NSLog(@"Accounts: %@", [[NXOAuth2AccountStore sharedStore] accounts]);
```

And here is the output:

```
2013-04-15 00:12:06.583 Catapult[68429:c07] Accounts: (
    "<NXOAuth2Account identifier:'1E415A5E-2572-4FBE-A345-E01AAD18E5DD' accountType:'com.cataputlcentral.api' accessToken:<NXOAuth2Token token:184cf28aa6377fe82c4f58ca1078c52ba4e0b415d01f6599d6e56370c41f9196 refreshToken:ea6b6378fad1806157405f01396adb4389fad074779cabceb8172b6591915470 expiresAt:2013-04-15 00:12:06 +0000 tokenType: Bearer> userData:(null)>"
)
```

As you can see the userData attribute is nil...

**Comment by anagromataf** [comment]
Seams to be a bug. Can you add a breakpoint at this line and see, if it gets called? https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2AccountStore.m#L534

**Comment by RobertAudi** [comment]
@anagromataf I added a breakpoint and the method does get called when I create an account but not when I retrieve the account, which is normal. But what is odd is that when I retrieve the account, the userData is not set even though is seemed set when I created the account.

**Comment by RobertAudi** [comment]
Any updates on that issue?

**Comment by anagromataf** [comment]
@AzizLight I'm sorry, I didn't had enough time to look into that issue.

**Comment by anagromataf** [comment]
@AzizLight Maybe you can checkout one more thing: The userData is archived together with the other account information with a keyed archiver. For this the methods [-[NXOAuth2Account encodeWithCoder:]](https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2Account.m#L181) and [-[NXOAuth2Account initWithCoder:]](https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2Account.m#L189) have to be called (and there should be the correct userData). Can you have a look at this?

**Comment by RobertAudi** [comment]
The problem is not when I create an account, it's when I retrieve one later on. When I create an account and then retrieve the account right after, the user data is set properly. But then when I change views (for example) and then try to retrieve the account, the user data is not there... I added NSLog statements in encodeWithCoder and initWithCoder. The two of them get called on account creation, but only encodeWithCoder gets called on account retrieval (which seems normal to me, but what do I know...).

**Comment by RobertAudi** [comment]
By the way, you can see the whole project in [here](https://github.com/AzizLight/Catapult/tree/user-data). Make sure to check out the user-data branch since that is where the problem lies

**Comment by RobertAudi** [comment]
I just realised that this issue is a bug in my implementation, not in the library. Sorry about that...
