### ISSUE TITLE
Request token with URL encoding [meetup]

### ISSUE THREAD

**Issue by PeterGrisson** [nxtbgthng/OAuth2Client#75]
I'd like to use OAuth2Client to connect to meetup.com using the "External Browser" method. This means that I get a redirect URI callback with a code, which then I need to use to get the token. I believe I need to use <code>[[NXOAuth2AccountStore sharedStore] handleRedirectURL:url]</code> to do this.

As per the meetup.com web site, I need to "make an HTTP application/x-www-form-urlencoded encoded POST request" to get the token (full details here: http://www.meetup.com/meetup_api/auth/ ).

It seems that <code>[[NXOAuth2AccountStore sharedStore] handleRedirectURL:url]</code> uses form encoding, not URL encoding, when it sends the request to get the token. Interestingly the <code>NXOAuth2Connection:applyParameters</code> method, which is used to prepare the token request, can do both URL and form encoding, but for POST requests it always uses the latter.

I was actually able to make the token request work by forcing the <code>NXOAuth2Connection:applyParameters</code> method to always do URL encoding, but obviously this is just a quick hack, not a long term solution.

Is there a parameter somewhere that I could set to achieve the same result? Or is this option missing from the library?

Thanks,
Peter

**Comment by anagromataf** [comment]
@PeterGrisson If I understand you right, you have to request the token with a GET request. If a modification in [-[NXOAuth2Client requestTokenWithAuthGrant:redirectURL:]](https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2Client.m#L309) solves your problem, we have to extend the framework in some way. One approach would be to store this information somehow in the settings dict for the account type in [NXOAuth2AccountStore](https://github.com/nxtbgthng/OAuth2Client/blob/master/Sources/OAuth2Client/NXOAuth2AccountStore.m#L264).

**Comment by ghost** [comment]
I have kind of the same Problem, But in my opinion it is not only set the HTTP-Method to POST and append the parameter to the URL. In this case I would use a GET. (I also suppose that this violates the security of the POST method)
IMO the library should support application/x-www-form-urlencoded in the way it supposed to be. Its just simply putting all the URL parameter in the request body.

It would be great if you could provide a interface to set the Content-Type for POST manually if needed.

**Comment by mario** [comment]
Can you please make this happen? I also need handleRedirectURL to do x-www-form-urlencoded.

**Comment by AndreasTextunes** [comment]
Hi @mario 
since Jul 15, 2014 this is implemented. check the commits ;-)

don't know why this is still open

**Comment by toto** [comment]
Sorry. Forget to close this.
