### ISSUE TITLE
oauthConnection error [37signals]

### ISSUE THREAD

**Issue by miharekar** [nxtbgthng/OAuth2Client#77]
First thanks for the library - we use it in our app and it's great.

But we've received a couple of supports with this error. We got them all fixed by telling our users to sign out and sign in again but still it's a pain in the ass and I don't know how to debug it. All we see in the logs is thousands of this:

```
-[NXOAuth2PostBodyStream open] Stream has been reopened after close
oauthConnection Error: {"error":"Missing code query parameter."}
```

Any idea what's going on and how to fix it?

As said, if user logs out and logs in again, everything works fine. This should probably raise an exception or at least throw an error in responseHandler block.

**Comment by stigi** [comment]
hi @mrfoto 

Can you tell me which API you're using the library with?
Errors that are logged with `oauthConnection Error:` are happening in the part of the library that is transparently handling the token exchange. They are repeated up to 4 times and if then are still failing the `oauthClient:didFailToGetAccessTokenWithError:` method of `NXOAuth2ClientDelegate` should be called (if implemented).

The message `Missing code query parameter` is returned from the API and could tell us what's wrong. It might be the case that the API is implementing a different Draft of OAuth2 than the library is build for.

**Comment by miharekar** [comment]
I'm using https://github.com/37signals/bcx-api/

**Comment by stigi** [comment]
Reading though their [docs on authenticating](https://github.com/37signals/api/blob/master/sections/authentication.md) it looks like they are using a different kind of auth2, requiring `type` instead of `grant_type` and so on. How did you configure the oauth2 client to be able to connect to their API in the first place?

**Comment by miharekar** [comment]
I didn't even know there are more OAuth2 specs :laughing: 

I included your lib with cocoapods then 

```
[[NXOAuth2AccountStore sharedStore] setClientID:@"***"
                                         secret:@"***"
                               authorizationURL:[NSURL URLWithString:@"https://launchpad.37signals.com/authorization/new?type=web_server"]
                                       tokenURL:[NSURL URLWithString:@"https://launchpad.37signals.com/authorization/token?type=web_server"]
                                    redirectURL:[NSURL URLWithString:@"***"]
                                 forAccountType:@"***"];
```

and it all works normally.

**Comment by miharekar** [comment]
But I did look up and down the internet for a OAuth2 library for Mac and only found yours and the one from Google which is terrible with tons of stupid defaults. So I guess I'll have to dive in and write my own/fork yours?

**Comment by stigi** [comment]
Ah, passing `type=web_server` in the query string of the URLs explains a lot ;)

I'm just setting up a test project talking to the 37signals API. Do you have a way to reproduce the `Missing code query parameter` issue?

Ideally we can bend this library a little to make it work with most of the APIs out there. I'm dreaming of a section in the wiki that describes things as the `type=web_server` query parameter and other configuration settings for each major API out there that claims to speak OAuth2 ;)

**Comment by miharekar** [comment]
Nope, that's exactly the problem. I think it might be when the token refresh happens but I have no idea how to test that - as said, I haven't really looked into OAuth2. But I'm not sure - from the supports we got it happened when users updated the app but I haven't changed a thing in the auth process so I have no idea. Maybe it's Keychain related.

As I said in the opening issue - I have no idea what's going on, so I asked you :laughing:

**Comment by stigi** [comment]
I'm here to help :)

I'll let you know if I figure something out.

**Comment by stigi** [comment]
Ok, Here's what I figured out.  The Problem is the token refresh. 37 signals are using an unspecified draft of the oauth2 spec, so I also can't find out how they expect the token refresh request to look like.

You can force the bug by changing the `-createConnection` method in `NXOAuth2Connection.h` to always go into the  `if ([tenSecondsAgo earlierDate:tokenExpiresAt] == tokenExpiresAt) {` branch.

I've opened an issue on their side: 37signals/bcx-api#87

**Comment by miharekar** [comment]
In the mean time, I found this:

> I believe what you want is as follows...
> 
> POST to https://launchpad.37signals.com/authorization/token with the following POST params:
> 
> type=refresh
> client_id=<your client id>
> redirect_uri=<your redirect uri>
> client_secret=<your client secret>
> refresh_token=<the refresh token you got when you created the access token
> 
> Be sure to set Content-Type to "application/x-www-form-urlencoded"

So I tried [hacking this](https://github.com/mrfoto/OAuth2Client/tree/37signals) in and now I get `{"error":"Missing client_id query parameter."}`

![screen shot 2013-06-11 at 14 47 57](https://f.cloud.github.com/assets/986645/636918/9be48c24-d295-11e2-8651-ddba2eb66d8f.png)

**Comment by miharekar** [comment]
Hmmm...now I tried to execute this request using EXACT SAME parameters with Chrome REST console and it went through perfectly and I got the `access_token` and `expires_in` back normally. There must be something weird going on when POSTing :confused:

**Comment by stigi** [comment]
@mrfoto I'll have a look tomorrow. Can't be toooo hard ;)

**Comment by miharekar** [comment]
@stigi So? Figured it out yet?

**Comment by stigi** [comment]
@mrfoto no, sorry. got torn away to another project. will need to free some time to look into this. but as we figured out until now it's the token refresh request. so you might manage to get it working by changing the request in the `-refreshAccessTokenAndRetryConnection:` method in `NXOAuth2Client.m`.

**Comment by miharekar** [comment]
@stigi hey, got time yet? I'm way to much noob in Objective-C to crack this one. Been trying for a while but I always give up and go work on something else :laughing: 

I figured it could be the `Content-Type` in `- (void)applyParameters:(NSDictionary *)parameters onRequest:(NSMutableURLRequest *)aRequest;` since [they say](https://github.com/37signals/bcx-api/issues/32) it should be `application/x-www-form-urlencoded`.

But when I changed to that I get `{"error":"Missing client_id query parameter."}` instead of the "regular" `{"error":"Missing code query parameter."}`. :confused:

**Comment by Khalid-Usman** [comment]
@stigi @mrfoto , I am calling the following api , to create todo. 

[NXOAuth2Request performMethod:@"POST"
                                                   onResource:url
                                              usingParameters:saveDic
                                                  withAccount:currAccount
                                          sendProgressHandler:^(unsigned long long bytesSend, unsigned long long bytesTotal) { 
                                          }
                                              responseHandler:^(NSURLResponse *response, NSData *responseData, NSError *error){

```
                                              if (!error) {
                                                  NSError *jsonParsingError = nil;
                                                  NSArray *jsonArr = [NSJSONSerialization JSONObjectWithData:responseData
                                                                                                     options:0 error:&jsonParsingError];
                                                  NSLog(@"%d",[jsonArr count]);

                                              }
                                          }];
                       }
```

Where, parameter equal to

NSMutableDictionary *saveDic = [[NSMutableDictionary alloc] init];
        [saveDic setObject:@"2012-03-27"forKey:@"due_at"];
        [saveDic setObject:assignId forKey:@"assignee[id]"];
        [saveDic setObject:@"Person" forKey:@"assignee[type]"];
        [saveDic setObject:self.todoTextView.text forKey:@"content"];

and currAccount equal to current account.

It showing me the following error.

-[NXOAuth2PostBodyStream open] Stream has been reopened after close
Error Domain=NXOAuth2HTTPErrorDomain Code=403 "HTTP Error: 403" UserInfo=0x796635f0 {NSLocalizedDescription=HTTP Error: 403}

Kindly let me how can i fix it.

Thanks 
Khalid
