### ISSUE TITLE
Passing dictionary resulted in "NXOAuth2PostBodyPart with illegal type"

### ISSUE THREAD

**Issue by vleango** [nxtbgthng/OAuth2Client#81]
My dictionary has another dictionary inside of it. When I try to use "PUT" with my NXOAuth2Request, i get this error: "NXOAuth2PostBodyPart with illegal type". Here is my dictionary:

{ "Person" => {"name"=>"John"} }

**Comment by vleango** [comment]
There doesn't seem to be a method for this (nsdictionary / hash). 
I need a hash to send to my rails app.

**Comment by vleango** [comment]
I just learned that passing the key like this works: Person[name]

**Comment by mattvague** [comment]
> I just learned that passing the key like this works: Person[name]
> @vleango can you reiterate what you mean by this? I'm having the same problem

**Comment by vleango** [comment]
@mattvague i'm not really good with rails, but i learned that if I needed {"person" => {"first" => "john", "last" => "denver"}} be sent as a param, I would need to send it like this: 

```
@{"person[first]" : "john", "person[last]" : "denver"};
```
