### ISSUE TITLE
Some help would be much-appreciated

### ISSUE THREAD

**Issue by ricburton** [nxtbgthng/OAuth2Client#83]
Hi there,

I've been doing my best to get this running but I'm not able to get the success and error blocks to work properly. Any advice would be much appreciated:

https://github.com/richardburton/README/blob/oauth2/source/AppDelegate.m
https://github.com/richardburton/README/blob/oauth2/source/RootViewController.m

**Comment by toto** [comment]
Not that this is not Stackoverflow but the issue tracker.

Also the code is gone by now, so I'm closing this.
