### ISSUE TITLE
Cannot POST JSON data

### ISSUE THREAD

**Issue by dwa012** [nxtbgthng/OAuth2Client#88]
I am using this to pull JSON data from my server with no trouble. 

I also need to send JSON data. I am trying to modify the library to take a dictionary to as a parameter and convert it to a JSON string and add the right header. It no longer crashes but the data is not sent to the server property.

I am modifying the NXOAuth2PostBodyPart class to do this. I am following the other code cases for the data.

```
else if ([content isKindOfClass:[NSDictionary class]]) {
        return [self initWithName:name dictContent:content];
    }
```

```
- (id)initWithName:(NSString *)name dictContent:(NSDictionary *)dictionary;
{
    NSMutableString *headers = [NSMutableString string];
    [headers appendString:@"Content-Type: application/json\r\n"];
    [headers appendString:@"\r\n"];

    NSData *jsonData = [NSJSONSerialization dataWithJSONObject:dictionary options:nil error:nil];
    NSString *jsonString = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];

    return [self initWithHeaders:headers dataContent:[jsonString dataUsingEncoding:NSUTF8StringEncoding]];
}
```

I cannot find any examples on POSTing data with your library, all the examples are for GET requests.

**Comment by toto** [comment]
No need to do so many changes. POSTing stuff should be better documented. Posting data works like this:

```
NSURL *url = …;
NXOAuth2Account *account = …;
NSDictionary *params = @{@"key": @"value"}; 
// note that the dictionary must contain only NSString objects as key or values.
NXOAuth2Request *request = [[NXOAuth2Request alloc] initWithResource:url
                  method:@"POST"
            parameters:params];
request.account = account; // <- Note this

[identifierRequest performRequestWithSendingProgressHandler:NULL
                                                responseHandler:^(NSURLResponse *response, NSData *responseData, NSError *error) {
   …
}];

```

This will send the parameters form encoded.

If you need to post raw JSON you can use the `NSURLRequest` compatibility layer:

```
NSDictionary *json = …;
NSData *bodyData = [NSJSONSerialization dataWithJSONObject:json options:nil error:nil];
NXOAuth2Account *account = …;
NXOAuth2Request *request =  [[NXOAuth2Request alloc] initWithResource:url
                                                                                                  method:@"POST"
                                                                                            parameters:nil];
request.account = account; // <- Note this
NSMutableURLRequest *urlRequest = [[request signedURLRequest] mutableCopy];
[urlRequest setValue:@"application/json"  forHTTPHeaderField:@"Content-Type"];
[urlRequest setHTTPBody:bodyData];
```

After this you can use a regular `NSURLConnection` like this:

```
[NSURLConnection sendAsynchronousRequest:urlRequest 
                  queue:nil 
                     completionHandler:^(NSURLResponse* response, NSData* data, NSError* connectionError) {
…
}];
```

**Comment by dwa012** [comment]
Worked perfectly! Thanks for responding so quickly.

**Comment by Khalid-Usman** [comment]
Create to-do

POST /projects/1/todolists/1/todos.json will add a new to-do to the specified to-do list from the parameters passed. The due_at parameter should be in ISO 8601 format (like "2012-03-27T16:00:00-05:00"). The assignee parameters need a type field with the Person specified. The id is then the id of the person who was assigned.
{
  "content": "This is my new thing!",
  "due_at": "2012-03-27",
  "assignee": {
    "id": 149087659,
    "type": "Person"
  }
}

I got the above from the following link and want to use it, 
https://github.com/basecamp/bcx-api/blob/master/sections/todos.md

NSURL *url = [NSURL URLWithString:@"https://basecamp.com/7-digit_id/projects/7-digit_other_id/todolists/1/todos.json"];
NXOAuth2Account *currAccount = (NXOAuth2Account *)[userAccount valueForKey:identifier];
NSDictionary *assigneeDic = [NSDictionary dictionaryWithObjectsAndKeys:assignId,@"id",@"Person",@"type", nil];
NSDictionary *dic = [NSDictionary dictionaryWithObjectsAndKeys:@"username",@"Username",@"password",@"Password",self.todoTextView.text,@"content",@"2015-01-12",@"due_at",assigneeDic,@"assignee", nil];

NXOAuth2Request *request = [[NXOAuth2Request alloc] initWithResource:url
                                                                      method:@"POST"
                                                                  parameters:dic];
        request.account = currAccount; // <- Note this

```
    [request performRequestWithSendingProgressHandler:NULL
                                                responseHandler:^(NSURLResponse *response, NSData *responseData, NSError *error) {
                                                    if (error) {
                                                        NSLog(@"Error");
                                                    } else {
                                                        NSLog(@"Success");
                                                    }
                                                }];
```

It always show me the following error. 

Error Domain=NXOAuth2HTTPErrorDomain Code=404 "HTTP Error: 404" UserInfo=0x7ae848b0 {NSLocalizedDescription=HTTP Error: 404}
