### ISSUE TITLE
authentication is not working

### ISSUE THREAD

**Issue by ghost** [nxtbgthng/OAuth2Client#89]
Hallo,

I'm using your library to connect to Readability API.

Here is the code:

---

``` cocoa
[[NXOAuth2AccountStore sharedStore] setClientID:@"key"
                                             secret:@"secret"
                                   authorizationURL:[NSURL URLWithString:@"https://www.readability.com/api/rest/v1/oauth/authorize"]
                                           tokenURL:[NSURL URLWithString:@"https://www.readability.com/api/rest/v1/oauth/access_token"]
                                        redirectURL:[NSURL URLWithString:"myapp"]
                                     forAccountType:@"App"]; 


[[NSNotificationCenter defaultCenter] addObserverForName:NXOAuth2AccountStoreAccountsDidChangeNotification
                                                      object:[NXOAuth2AccountStore sharedStore]
                                                       queue:nil
                                                  usingBlock:^(NSNotification *aNotification){
                                                      for (NXOAuth2Account *anAccount in [[NXOAuth2AccountStore sharedStore] accountsWithAccountType:@"App"]) {
                                                          NSLog(@"SUCCESS\n");
                                                          account = anAccount;
                                                      };
                                                  }];


[[NSNotificationCenter defaultCenter] addObserverForName:NXOAuth2AccountStoreDidFailToRequestAccessNotification
                                    object:[NXOAuth2AccountStore sharedStore]
                                     queue:nil
                                usingBlock:^(NSNotification *aNotification){
                                    NSLog(@"NOT WORKING\n");
                                }];


[[NXOAuth2AccountStore sharedStore] requestAccessToAccountWithType:@"App"
                                              username:username password:password];

```

---

But it is not working, i get always an error:
error   NSURLError \*    domain: @"NSURLErrorDomain" - code: -1005  
@"The network connection was lost." 

and log:
[NXOAuth2PostBodyStream open] Stream has been reopened after close
[NXOAuth2PostBodyStream open] Stream has been reopened after close

What is wrong? Is it bug of library?
Please help me to fix it.

Ruslan.

**Comment by toto** [comment]
Without looking into this more thoroughly three remarks:
1. Your redirect URL is not a valid URL. You need at least a scheme. E.g. `myapp:`
2. `[NXOAuth2PostBodyStream open] Stream has been reopened after close` is no sign of trouble, don't worry
3. Are you sure Readability supports password based login with OAuth2? Most services don't do that (App.net and Soundcloud are two notable exceptions I know of.

**Comment by toto** [comment]
From glancing over their API docs it looks like they do not support OAuth2 but only OAuth1 and XAuth.

**Comment by ghost** [comment]
Thanks a lot toto!! Okey, i will learn more about schemes. I'm a new in this area.

Yes, you are right, they do not support oauth2, yesterday i've made some requests with "oauth_version=2.0" parameter and server responds that not support this version.
