### ISSUE TITLE
Make authentication scope available to library clients

### ISSUE THREAD

**Issue by robb** [nxtbgthng/OAuth2Client#9]
As a user of the library, I need to be able to access the scope of the current authentication to know which requests I am allowed to send.

As this library reflects draft 10 of the OAuth2 spec, relevant information can be found at http://tools.ietf.org/html/draft-ietf-oauth-v2-10#section-3

**Comment by robb** [comment]
Here’s the description of the scope from the spec

```
scope
     OPTIONAL.  The scope of the access request expressed as a list
     of space-delimited strings.  The value of the "scope" parameter
     is defined by the authorization server.  If the value contains
     multiple space-delimited strings, their order does not matter,
     and each string adds an additional access range to the
     requested scope.
```

**Comment by toto** [comment]
This can be done for a while now :-)

**Comment by stigi** [comment]
2yo!? omg!
